// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1KQAL5bdWlULMQZal8Sfo0UbJ8epoQE',
    appId: '1:400582900642:web:98d3f1ab7e3c057dbf90fb',
    messagingSenderId: '400582900642',
    projectId: 'trombarea-lewan',
    authDomain: 'trombarea-lewan.firebaseapp.com',
    storageBucket: 'trombarea-lewan.appspot.com',
    measurementId: 'G-DQNTPHHCLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYRvajTGIxUcfgZd_jEvO2CUPJ7xUz7mg',
    appId: '1:400582900642:android:874a4c760c04adb8bf90fb',
    messagingSenderId: '400582900642',
    projectId: 'trombarea-lewan',
    storageBucket: 'trombarea-lewan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOhC9QqsSpfyeA3MMeX4Px9uOT7ZkmvpA',
    appId: '1:400582900642:ios:728a7c17e1d8cb66bf90fb',
    messagingSenderId: '400582900642',
    projectId: 'trombarea-lewan',
    storageBucket: 'trombarea-lewan.appspot.com',
    iosClientId: '400582900642-772qhdg59heoq9kusci7914vninl9ihn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trombarea',
  );
}
