---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install useful packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3-pip
    - python3-dev
    - python3-psycopg2
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-setuptools

- name: Update pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Upgrade setuptools
  pip:
    name: setuptools
    state: latest
    executable: pip3
