jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    ldap:
      configurations:
        - groupMembershipStrategy:
            fromUserRecord:
              attributeName: "memberOf"
          inhibitInferRootDN: false
          rootDN: "dc=acme,dc=org"
          server: "ldaps://ldap.acme.org:1636"
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}

        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}

        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}

        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
              - "Job/Workspace"
              - "Job/Read"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "nasso"

jobs:
  - file: /job_dsl.groovy

tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git

credentials:
  system:
    domainCredentials:  
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh_with_passphrase_provided
              username: ssh_root
              passphrase: ${SSH_KEY_PASSWORD}
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_PRIVATE_KEY}
